### ISSUE TITLE
Possible dev env bug, and some questions

### ISSUE THREAD

**Issue by Nick011** [scrtlabs/secret-sdk-python#5]
- secret_sdk version: Main
- Python version: 3.10.2
- Operating System: Manjaro Linux (Arch based)

### Intro

Hello, I've reviewed and tested this library and I'm finding the code quality and developer experience to be quite good. You guys are off to a great start on this.

### Description

I had to upgrade uvloop and run `poetry lock` to get the deps to install.
  - This might be a bug that needs a PR

### What I Did

- `git clone (secret-sdk-python)`
- `poetry install`
- [uvloop error traceback](https://gist.github.com/Nick011/8b96ce44f03ee29ee86a48d596a51435)
- LMK if you want me to try things to reproduce but, I've solved the problem by [upgrading the project to the latest uvloop](https://github.com/Nick011/secret-sdk-python/pull/1/files) stable version.

### Additionally

It appears this library is not Secret specific. It's possibly a superset.  Which is actually a great feature. I was able to [early exit this function](https://github.com/Nick011/secret-sdk-python/pull/1/files#diff-6673005e60336d707afbd7c10ad3ab0672ced901c38cbde9831ecd43b636204aR106) and get the client to connect to an osmosis node. Presumably because all IBC interfaces are the same (similar?). I'm working on a project that requires interacting with multiple cosmos chains. This client appears to have enough of what I need to do so.

Can you tell me more about what this function does? It doesn't appear be required to make requests to the scrt network. Can we make it optional so that I can use this lib as a generic cosmos client in addition to the scrt specific features it offers?

Thanks, 
Nick

**Comment by zackgow** [comment]
Thanks for the notice on `uvloop`.

As for the function, you can read up on the encryption details [here](https://docs.scrt.network/protocol/encryption-specs.html#transaction-encryption).

As of now, we have no interest in this being a generic cosmos client, but feel free to fork the repo and make your own edits locally.

**Comment by Nick011** [comment]
Works for me. Glad I could provide some help on the UV loop issue.

Closing this.

**Comment by Nick011** [comment]
Also, great job on this. You guys are good and know what's up!
